### ISSUE TITLE
Leaflet 1.0.3 issue

### ISSUE THREAD

**Issue by pmikla14** [vogdb/Leaflet.ActiveLayers#10]
Hi!

I'm currently using the activeLayers plugin with leaflet 0.7, but I would like to update to leaflet 1.0
I took the latest activeLayers version (0.3.0) and the lastest leaflet version (1.0.3), but I'm having troubles with it.

This is how I implement the plugin: 
```
layers = L.control.activeLayers(baseLayers, topLayers);
layers.addTo(map);
```
Using leaflet-src.js and src/activeLayers.js I get the following error in the console:

```
Uncaught TypeError: layer.on is not a function
    at NewClass._addLayer (Control.Layers.js:223)
    at NewClass.initialize (Control.Layers.js:86)
    at new NewClass (Class.js:21)
    at Function.L.control.activeLayers (activeLayers.js:136)
    at init (main.js:410)
```

Can you help me, I ran out of ideas... 
Thanks, Philipp!

**Comment by vogdb** [comment]
I've tried to run project's tests with leaflet@1.0.3. They work. You need to provide the full listing of yours if you want help.

**Comment by vogdb** [comment]
@pmikla14 ?

**Comment by pmikla14** [comment]
Sorry for the late answer!

Thanks for testing, if it works with pure leaflet 1.0.3, then there must be troubles with other plugins/custom modifications. 
I will look for myself, thanks for the support :)

Philipp
